-- ================================================================
-- Abnormal Management System (AMS) - Database Schema
-- Oracle Database Script
-- Version: 1.1
-- ================================================================

-- ================================================================
-- DEPARTMENT
-- ================================================================
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID      NUMBER(19)     NOT NULL,
    DEPARTMENT_CODE    VARCHAR2(30)   NOT NULL,
    DEPARTMENT_NAME    VARCHAR2(100)  NOT NULL,
    DESCRIPTION        VARCHAR2(500),
    STATUS             VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
    SORT_ORDER         NUMBER(10)     DEFAULT 0 NOT NULL,
    CREATE_TIME        TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME        TIMESTAMP(6),
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT UQ_DEPARTMENT_CODE UNIQUE (DEPARTMENT_CODE),
    CONSTRAINT CHK_DEPARTMENT_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

-- ================================================================
-- PROCESS_STEP
-- ================================================================
CREATE TABLE PROCESS_STEP (
    PROCESS_STEP_ID    NUMBER(19)     NOT NULL,
    STEP_CODE          VARCHAR2(30)   NOT NULL,
    STEP_NAME          VARCHAR2(100)  NOT NULL,
    DESCRIPTION        VARCHAR2(500),
    STATUS             VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
    SORT_ORDER         NUMBER(10)     DEFAULT 0 NOT NULL,
    CREATE_TIME        TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME        TIMESTAMP(6),
    CONSTRAINT PK_PROCESS_STEP PRIMARY KEY (PROCESS_STEP_ID),
    CONSTRAINT UQ_PROCESS_STEP_CODE UNIQUE (STEP_CODE),
    CONSTRAINT CHK_PROCESS_STEP_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

-- ================================================================
-- USER_INFO
-- ================================================================
CREATE TABLE USER_INFO (
    USER_ID            NUMBER(19)     NOT NULL,
    USERNAME           VARCHAR2(50)   NOT NULL,
    PASSWORD_HASH      VARCHAR2(255)  NOT NULL,
    FULL_NAME          VARCHAR2(100)  NOT NULL,
    EMAIL              VARCHAR2(100),
    DEPARTMENT_ID      NUMBER(19),
    ROLE               VARCHAR2(20)   DEFAULT 'USER' NOT NULL,
    STATUS             VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
    CREATE_TIME        TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME        TIMESTAMP(6),
    CONSTRAINT PK_USER_INFO PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_USER_INFO_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UQ_USER_INFO_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_USER_INFO_ROLE CHECK (ROLE IN ('ADMIN', 'USER')),
    CONSTRAINT CHK_USER_INFO_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT FK_USER_INFO_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (DEPARTMENT_ID)
);

-- ================================================================
-- ABNORMAL
-- ================================================================
CREATE TABLE ABNORMAL (
    ABNORMAL_ID        NUMBER(19)     NOT NULL,
    ABNORMAL_NO        VARCHAR2(30)   NOT NULL,
    TITLE              VARCHAR2(200)  NOT NULL,
    DESCRIPTION        CLOB           NOT NULL,
    PROCESS_STEP_ID    NUMBER(19)     NOT NULL,
    DEPARTMENT_ID      NUMBER(19)     NOT NULL,
    PRIORITY           VARCHAR2(20)   DEFAULT 'MEDIUM' NOT NULL,
    STATUS             VARCHAR2(20)   DEFAULT 'OPEN' NOT NULL,
    DUE_DATE           DATE,
    REPORTER_ID        NUMBER(19)     NOT NULL,
    CREATE_TIME        TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME        TIMESTAMP(6),
    UPDATE_BY          NUMBER(19),
    CONSTRAINT PK_ABNORMAL PRIMARY KEY (ABNORMAL_ID),
    CONSTRAINT UQ_ABNORMAL_NO UNIQUE (ABNORMAL_NO),
    CONSTRAINT CHK_ABNORMAL_PRIORITY CHECK (PRIORITY IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT CHK_ABNORMAL_STATUS CHECK (STATUS IN ('OPEN', 'PROCESSING', 'CLOSED')),
    CONSTRAINT FK_ABNORMAL_PROCESS_STEP FOREIGN KEY (PROCESS_STEP_ID)
        REFERENCES PROCESS_STEP (PROCESS_STEP_ID),
    CONSTRAINT FK_ABNORMAL_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (DEPARTMENT_ID),
    CONSTRAINT FK_ABNORMAL_REPORTER FOREIGN KEY (REPORTER_ID)
        REFERENCES USER_INFO (USER_ID),
    CONSTRAINT FK_ABNORMAL_UPDATE_BY FOREIGN KEY (UPDATE_BY)
        REFERENCES USER_INFO (USER_ID)
);

-- ================================================================
-- ABNORMAL_IMAGE
-- ================================================================
CREATE TABLE ABNORMAL_IMAGE (
    IMAGE_ID             NUMBER(19)     NOT NULL,
    ABNORMAL_ID          NUMBER(19)     NOT NULL,
    ORIGINAL_FILE_NAME   VARCHAR2(255)  NOT NULL,
    STORED_FILE_NAME     VARCHAR2(255)  NOT NULL,
    FILE_PATH            VARCHAR2(500)  NOT NULL,
    FILE_SIZE            NUMBER(19)     NOT NULL,
    MIME_TYPE            VARCHAR2(100)  NOT NULL,
    UPLOADED_BY          NUMBER(19)     NOT NULL,
    UPLOADED_TIME        TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ABNORMAL_IMAGE PRIMARY KEY (IMAGE_ID),
    CONSTRAINT CHK_IMAGE_FILE_SIZE CHECK (FILE_SIZE > 0),
    CONSTRAINT CHK_IMAGE_MIME_TYPE CHECK (MIME_TYPE IN ('image/jpeg', 'image/png')),
    CONSTRAINT FK_IMAGE_ABNORMAL FOREIGN KEY (ABNORMAL_ID)
        REFERENCES ABNORMAL (ABNORMAL_ID) ON DELETE CASCADE,
    CONSTRAINT FK_IMAGE_UPLOADED_BY FOREIGN KEY (UPLOADED_BY)
        REFERENCES USER_INFO (USER_ID)
);

-- ================================================================
-- AUDIT_LOG
-- ================================================================
CREATE TABLE AUDIT_LOG (
    AUDIT_ID         NUMBER(19)      NOT NULL,
    USER_ID          NUMBER(19)      NOT NULL,
    ACTION           VARCHAR2(30)    NOT NULL,
    ENTITY_NAME      VARCHAR2(100)   NOT NULL,
    ENTITY_ID        NUMBER(19),
    ENTITY_NO        VARCHAR2(50),
    DESCRIPTION      VARCHAR2(1000),
    ACTION_TIME      TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    IP_ADDRESS       VARCHAR2(50),
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (AUDIT_ID),
    CONSTRAINT CHK_AUDIT_ACTION CHECK (ACTION IN ('CREATE', 'UPDATE', 'DELETE')),
    CONSTRAINT FK_AUDIT_USER FOREIGN KEY (USER_ID)
        REFERENCES USER_INFO (USER_ID)
);

-- ================================================================
-- ABNORMAL_NO_COUNTER
-- ================================================================
CREATE TABLE ABNORMAL_NO_COUNTER (
    SEQ_DATE        DATE           NOT NULL,
    LAST_NUMBER     NUMBER(5)      DEFAULT 0 NOT NULL,
    CREATE_TIME     TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME     TIMESTAMP(6),
    CONSTRAINT PK_ABNORMAL_NO_COUNTER PRIMARY KEY (SEQ_DATE),
    CONSTRAINT CHK_ABNORMAL_NO_COUNTER_NUM CHECK (LAST_NUMBER >= 0 AND LAST_NUMBER <= 99999)
);

-- ================================================================
-- SEQUENCES
-- ================================================================
CREATE SEQUENCE SEQ_USER_INFO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PROCESS_STEP START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DEPARTMENT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ABNORMAL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ABNORMAL_IMAGE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AUDIT_LOG START WITH 1 INCREMENT BY 1 NOCACHE;

-- ================================================================
-- INDEXES
-- ================================================================
CREATE INDEX IDX_USER_INFO_DEPARTMENT ON USER_INFO (DEPARTMENT_ID);
CREATE INDEX IDX_USER_INFO_STATUS ON USER_INFO (STATUS);

CREATE INDEX IDX_PROCESS_STEP_STATUS ON PROCESS_STEP (STATUS);
CREATE INDEX IDX_DEPARTMENT_STATUS ON DEPARTMENT (STATUS);

CREATE INDEX IDX_ABNORMAL_STATUS ON ABNORMAL (STATUS);
CREATE INDEX IDX_ABNORMAL_PRIORITY ON ABNORMAL (PRIORITY);
CREATE INDEX IDX_ABNORMAL_PROCESS_STEP ON ABNORMAL (PROCESS_STEP_ID);
CREATE INDEX IDX_ABNORMAL_DEPARTMENT ON ABNORMAL (DEPARTMENT_ID);
CREATE INDEX IDX_ABNORMAL_REPORTER ON ABNORMAL (REPORTER_ID);
CREATE INDEX IDX_ABNORMAL_CREATE_TIME ON ABNORMAL (CREATE_TIME);
CREATE INDEX IDX_ABNORMAL_DUE_DATE ON ABNORMAL (DUE_DATE);
CREATE INDEX IDX_ABNORMAL_UPDATE_BY ON ABNORMAL (UPDATE_BY);
CREATE INDEX IDX_ABNORMAL_LIST_01 ON ABNORMAL (STATUS, PRIORITY, CREATE_TIME);
CREATE INDEX IDX_ABNORMAL_SEARCH_01 ON ABNORMAL (ABNORMAL_NO, TITLE);

CREATE INDEX IDX_ABNORMAL_IMAGE_ABNORMAL ON ABNORMAL_IMAGE (ABNORMAL_ID);

CREATE INDEX IDX_AUDIT_LOG_USER_TIME ON AUDIT_LOG (USER_ID, ACTION_TIME);
CREATE INDEX IDX_AUDIT_LOG_ENTITY ON AUDIT_LOG (ENTITY_NAME, ENTITY_ID);
CREATE INDEX IDX_AUDIT_LOG_ACTION_TIME ON AUDIT_LOG (ACTION_TIME);

-- ================================================================
-- SEED DATA
-- ================================================================

-- Default Departments
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_CODE, DEPARTMENT_NAME, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_DEPARTMENT.NEXTVAL, 'DEPT-PROD', 'Production', 'Production department', 'ACTIVE', 1);

INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_CODE, DEPARTMENT_NAME, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_DEPARTMENT.NEXTVAL, 'DEPT-QA', 'Quality Assurance', 'QA department', 'ACTIVE', 2);

INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_CODE, DEPARTMENT_NAME, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_DEPARTMENT.NEXTVAL, 'DEPT-MAINT', 'Maintenance', 'Maintenance department', 'ACTIVE', 3);

INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_CODE, DEPARTMENT_NAME, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_DEPARTMENT.NEXTVAL, 'DEPT-PLAN', 'Planning', 'Planning department', 'ACTIVE', 4);

-- Default Process Steps
INSERT INTO PROCESS_STEP (PROCESS_STEP_ID, STEP_CODE, STEP_NAME, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_PROCESS_STEP.NEXTVAL, 'STEP-010', 'Cutting', 'Cutting process', 'ACTIVE', 1);

INSERT INTO PROCESS_STEP (PROCESS_STEP_ID, STEP_CODE, STEP_NAME, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_PROCESS_STEP.NEXTVAL, 'STEP-020', 'Assembly', 'Assembly process', 'ACTIVE', 2);

INSERT INTO PROCESS_STEP (PROCESS_STEP_ID, STEP_CODE, STEP_NAME, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_PROCESS_STEP.NEXTVAL, 'STEP-030', 'Inspection', 'Inspection process', 'ACTIVE', 3);

INSERT INTO PROCESS_STEP (PROCESS_STEP_ID, STEP_CODE, STEP_NAME, DESCRIPTION, STATUS, SORT_ORDER)
VALUES (SEQ_PROCESS_STEP.NEXTVAL, 'STEP-040', 'Packing', 'Packing process', 'ACTIVE', 4);

-- Default Admin User (password: admin123, BCrypt hashed)
-- Hash generated with BCrypt, cost factor 10
INSERT INTO USER_INFO (USER_ID, USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, DEPARTMENT_ID, ROLE, STATUS)
VALUES (SEQ_USER_INFO.NEXTVAL, 'admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lqkkO9QS3TzCjH3rS', 'System Administrator', 'admin@ams.local', 
        (SELECT DEPARTMENT_ID FROM DEPARTMENT WHERE DEPARTMENT_CODE = 'DEPT-PROD'), 'ADMIN', 'ACTIVE');

COMMIT;
